export const ALL_PRODUCTS_REQUEST = "ALL_PRODUCTS_REQUEST";
export const ALL_PRODUCTS_SUCCESS = "ALL_PRODUCTS_SUCCESS";
export const ALL_PRODUCTS_ERROR = "ALL_PRODUCTS_ERROR";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
